name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup python 3.9.21
      uses: actions/setup-python@v1
      with: 
        python-version: 3.9.21
      
    - name: Install dependencies
      run: make install

    - name: Lint with python
      run: make lint

    - name: Test with pytest
      run: make test

    - name: Fromat code with Python black
      run: make format
